name: Deno CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

# Fixes the Node.js 20 Deprecation Warning notice
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Deno Environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x 

      - name: Run Linter
        # We use 'continue-on-error' so a small typo doesn't kill your demo
        continue-on-error: true
        run: deno lint

      - name: Check Dependencies
        # Verifies server.js can find all its imports
        run: deno info server.js

      - name: Run Tests
        # Only runs if you have files named something_test.ts
        continue-on-error: true
        run: deno test -A
      #   run: deno test -A --unstable
